openapi: 3.1.0
info:
  title: "Customers API"
  description: "REST API for managing customers"
  version: 1.0.0

servers:
  - url: 'http://localhost:8080'

tags:
  - name: Endpoints

paths:
  /api/v1/customers/register:
    post:
      tags: [ Endpoints ]
      summary: "Registers new customer"
      requestBody:
        required: true
        description: "Create customer request body"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerRequestBody'

            example:
              username: "askie01"
              password: "askie01"
              firstName: "adam"
              lastName: "pawlowski"
              email: "adam.pawlowski@example.com"
              mobileNumber: "123456789"

      responses:
        '201':
          description: "Customer registered successfully"

  /api/v1/customers/details:
    get:
      tags: [ Endpoints ]
      security:
        - basicAuth: [ ]
      summary: "Retrieves customer details"

      responses:
        '200':
          description: "Customer details"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDetailsResponseBody'

              example:
                firstName: "adam"
                lastName: "pawlowski"
                email: "adam.pawlowski@example.com"
                mobileNumber: "123456789"

    put:
      tags: [ Endpoints ]
      security:
        - basicAuth: [ ]
      summary: "Updates customer details"
      requestBody:
        required: true
        description: "Update customer details request body"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCustomerDetailsRequestBody'

            example:
              firstName: "adam"
              lastName: "kowalski"
              email: "adam.kowalski@example.com"
              mobileNumber: "987654321"

      responses:
        '204':
          description: "Customer details updated successfully"

  /api/v1/customers/image/{username}:
    get:
      tags: [ Endpoints ]
      summary: "Retrieves customer image"
      parameters:
        - name: username
          in: path
          required: true
          description: "Customer username"
          schema:
            type: string
            example: "askie01"

      responses:
        '200':
          description: "Customer image"
          content:
            image/jpeg:
              schema:
                type: string
                format: binary

  /api/v1/customers/search:
    get:
      tags: [ Endpoints ]
      summary: "Retrieves customer profiles"
      parameters:
        - name: query
          in: query
          required: false
          description: "Search phrase (username, email, etc.)"
          schema:
            type: string
            default: "askie01"

        - name: page
          in: query
          required: false
          description: "Page number (0-based)"
          schema:
            type: integer
            example: 0

        - name: size
          in: query
          required: false
          description: "Page size"
          schema:
            type: integer
            example: 10

        - name: sort
          in: query
          required: false
          description: "Sorting criteria: property, (asc|desc)"
          schema:
            type: string
            example: "username,asc"

      responses:
        '200':
          description: "Paged customer profiles"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerProfileResponseBody'

              example:
                - username: "askie01"
                  firstName: "adam"
                  lastName: "pawlowski"

                - username: "AniaKowalska"
                  firstName: "ania"
                  lastName: "kowalska"

  /api/v1/customers/profile/{username}:
    get:
      tags: [ Endpoints ]
      summary: "Retrieves customer profile"
      parameters:
        - name: username
          in: path
          required: true
          description: "Customer username"
          schema:
            type: string
            example: "askie01"

      responses:
        '200':
          description: "Customer profile"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerProfileResponseBody'

              example:
                firstName: "adam"
                lastName: "pawlowski"
                email: "adam.pawlowski@example.com"
                mobileNumber: "123456789"

  /api/v1/customers/password:
    put:
      tags: [ Endpoints ]
      security:
        - basicAuth: [ ]
      summary: "Updates customer password"
      requestBody:
        required: true
        description: "Update customer password request body"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCustomerPasswordRequestBody'

            example:
              oldPassword: "askie01"
              newPassword: "askie02"

      responses:
        '204':
          description: "Customer password updated successfully"

  /api/v1/customers/image:
    put:
      tags: [ Endpoints ]
      security:
        - basicAuth: [ ]
      summary: "Updates customer image"
      requestBody:
        required: true
        description: "New image request body"
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary

      responses:
        '204':
          description: "Image updated successfully"

  /api/v1/customers/image/restore:
    put:
      tags: [ Endpoints ]
      security:
        - basicAuth: [ ]
      summary: "Restores customer image to default"

      responses:
        '204':
          description: "Customer image restored to default successfully"

  /api/v1/customers:
    delete:
      tags: [ Endpoints ]
      security:
        - basicAuth: [ ]
      summary: "Deletes customer account"

      responses:
        '204':
          description: "Customer deleted successfully"

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:
    CreateCustomerRequestBody:
      type: object
      required: [
        username,
        password,
        firstName,
        lastName,
        email,
        mobileNumber
      ]
      properties:
        username:
          type: string
          minLength: 3

        password:
          type: string
          minLength: 3

        firstName:
          type: string
          minLength: 3

        lastName:
          type: string
          minLength: 3

        email:
          type: string

        mobileNumber:
          type: string
          minLength: 9

    CustomerDetailsResponseBody:
      type: object
      required: [
        firstName,
        lastName,
        email,
        mobileNumber
      ]
      properties:
        firstName:
          type: string

        lastName:
          type: string

        email:
          type: string

        mobileNumber:
          type: string

    CustomerProfileResponseBody:
      type: object
      required: [
        username,
        firstName,
        lastName
      ]
      properties:
        username:
          type: string

        firstName:
          type: string

        lastName:
          type: string

    UpdateCustomerDetailsRequestBody:
      type: object
      required: [
        firstName,
        lastName,
        email,
        mobileNumber
      ]
      properties:
        firstName:
          type: string
          minLength: 3

        lastName:
          type: string
          minLength: 3

        email:
          type: string
          minLength: 1

        mobileNumber:
          type: string
          minLength: 9

    UpdateCustomerPasswordRequestBody:
      type: object
      required: [
        oldPassword,
        newPassword
      ]
      properties:
        oldPassword:
          type: string
          minLength: 3

        newPassword:
          type: string
          minLength: 3